# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.1
      - image: tvachon/rex-db-dev:latest
        environment:
          POSTGRES_TEST_DB=rex-db_test

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache: # special step to restore the dependency cache
          keys:
            - v1-dependencies-{{ checksum "package.json" }}-{{ checksum "ui/package.json" }}-{{ checksum "api/package.json" }}-{{ checksum "schema/package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache: # special step to save the dependency cache
          paths:
            - ./node_modules
            - ./ui/node_modules
            - ./api/node_modules
            - ./schema/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum "ui/package.json" }}-{{ checksum "api/package.json" }}-{{ checksum "schema/package.json" }}
      # run tests!
      - run: npm run ui:test
      - run: npm run api:test
